# Generated by Django 5.1.1 on 2024-09-17 12:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('descriptio', models.CharField(max_length=254)),
                ('timestamp', models.CharField(max_length=24)),
                ('begin', models.CharField(max_length=24)),
                ('end', models.CharField(max_length=24)),
                ('altitudemo', models.CharField(max_length=254)),
                ('tessellate', models.BigIntegerField()),
                ('extrude', models.BigIntegerField()),
                ('visibility', models.BigIntegerField()),
                ('draworder', models.BigIntegerField()),
                ('icon', models.CharField(max_length=254)),
                ('snippet', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Clinics',
            },
        ),
    ]
