# Generated by Django 5.1.1 on 2024-09-17 13:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('objectid_1', models.FloatField()),
                ('admin3name', models.CharField(max_length=254)),
                ('admin3pcod', models.CharField(max_length=254)),
                ('admin2name', models.CharField(max_length=254)),
                ('admin2pcod', models.CharField(max_length=254)),
                ('admin1name', models.CharField(max_length=254)),
                ('admin1pcod', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('case_recor', models.CharField(max_length=254)),
                ('num_of_cas', models.CharField(max_length=254)),
                ('hotspot', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
