# Generated by Django 5.1.1 on 2024-09-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_wards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wards',
            options={'verbose_name_plural': 'Wards'},
        ),
        migrations.AlterField(
            model_name='wards',
            name='case_recor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wards',
            name='hotspot',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wards',
            name='num_of_cas',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
